source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
## ignore warning
inhibit_all_warnings!
target 'MHDevelopExample' do
    
#########  YYKit ###############
#pod 'YYKit'                             , '~> 1.0.9'

# YYKit 的一套分类
pod 'YYCategories'                      , '~> 1.0.4'
# 富文本
pod 'YYText'                            , '~> 1.0.5'
# 字典转模型
pod 'YYModel'                           , '~> 1.0.4'
# YYImage
pod 'YYImage'                           , '~> 1.0.4'
# webP
pod 'YYImage/WebP'
# 高性能的 iOS 缓存框架
pod 'YYCache'                           , '~> 1.0.4'
# 高性能的 iOS 异步图像加载框架。
pod 'YYWebImage'                        , '~> 1.0.5'
# iOS 键盘监听管理工具
pod 'YYKeyboardManager'                 , '~> 1.0.1'
# iOS 全局并发队列管理工具
pod 'YYDispatchQueuePool'               , '~> 1.0'
# iOS 异步绘制与显示的工具
pod 'YYAsyncLayer'                      , '~> 1.0'

# AutoLayout
pod 'Masonry', '~> 1.0.1'

# 缓存tableViewCell的高度
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'

# 字典转模型
pod 'MJExtension', '~> 3.0.13'


# 颜色分类
pod 'Colours', '~> 5.13.0'

# 根据颜色 生成一张图片
pod 'UIImage+ImageWithColor', '~> 1.3'

# HUD
pod 'MBProgressHUD', '~> 1.0.0'

# HUD
pod 'SVProgressHUD', '~> 2.0.3'

# 侧滑手势
pod 'FDFullscreenPopGesture', '~> 1.1'

# 数据库
pod 'FMDB', '~> 2.6.2'

# 环形进度条
pod 'DACircularProgress', '~> 2.3.1'

# 消息链
pod 'ReactiveCocoa','2.5'

# 网络请求
pod 'AFNetworking', '~> 3.1.0'

# 图片缓存
pod 'SDWebImage', '~> 4.0.0'

# UIView模糊
pod 'FXBlurView', '~> 1.6.4'

# WebSocket
pod 'SocketRocket', '~> 0.5.1'

# badgeValue
pod 'WZLBadge', '~> 1.2.5'
pod 'JSBadgeView', '~> 1.4.1'

# 文件压缩与解压
pod 'SSZipArchive', '~> 1.6.2'

# 苹果内购
pod 'RMStore', '~> 0.7.1'



# 菊花activity
pod 'MMMaterialDesignSpinner', '~> 0.2.3'

# 类似网易新闻的标签栏
pod 'YZDisplayViewController', '~> 1.0.6'

#刷新控件
pod 'MJRefresh', '~> 3.1.12'

#FPS检测
pod 'JPFPSStatus', '~> 0.1'

#打印一切
pod 'LxDBAnything', '~> 1.1.0'

# view的圆角处理 避免离屏渲染
# pod 'JMRoundedCorner'                   , '~> 1.2.1'
pod 'HYBImageCliped'                    , '~> 2.2.4'
pod 'ZYCornerRadius'                    , '~> 1.0.2'
pod 'HJCornerRadius', :git => 'https://github.com/panghaijiao/HJCornerRadius.git'

# 图片轮播器 由于头文件问题 手动导入
# pod 'SDCycleScrollView'               , '~> 1.66'

#########  Category  #########
# 非常强大的Objective-C库的扩展
pod 'libextobjc'                        , '~> 0.4.1'

# UI block
pod 'BlocksKit'                         , '~> 2.2.5'

# 图片浏览器
pod 'PYPhotoBrowser'                    , '~> 1.5.0'

# FaceBook‘s KVO（优雅的代替系统原生的KVO）
pod 'KVOController'                     , '~> 1.2.0'

# FaceBook‘s 内存分析工具 其中包括了：FBAllocationTracker 和 FBRetainCycleDetector两个工具
pod 'FBMemoryProfiler'

# 瀑布流
pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.6'
end
